
name: Deploy

on:
  schedule:
    - cron:  '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Creating Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{(date +'%y.%W')}}
          release_name: ${{ env.RELEASE_TAG }}
          body_path: .github/release.md
          draft: false
          prerelease: false
          
