# This is a basic workflow to help you get started with Actions

- name: Git Release
  # You may pin to the exact commit or the version.
  # uses: anton-yurchenko/git-release@aca5d54f34fd7fee889f093b67161bc7b9611d81
  uses: anton-yurchenko/git-release@v3.4.3
  with:
    # Release Assets
    args: # optional
